# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05bf3a628d4f2e5c90e8522d9cb453b654f6c78c342e6d978a5768a0270d1484d2a2e8aa4b512313cc27f8712efbaa3af8bf996b33a8648218910d91e7d9f2f7

test:
  secret_key_base: 0f2b5574ccf7de66e4ffc068899bcc6dc4b495a922a17d5019fd66f67457e52bc21dd19459ecec6f707ca29ef23ce9972bb8b0cf7235615f956d7e2d3099cfdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
